Repository Subhadeep3902/pocketgpt, pull requests merged in 2024-06, with the labels that each got.

#6 Chatbot gemini
  .env.example
  environment.d.ts
  package-lock.json
  package.json
  src/app/gemini/page.tsx
  tsconfig.json
Labels: VSoC’24, HARD, BONUS-50

#8 Chatbot gemini : code syntax and custom scrollbar
  package-lock.json
  package.json
  src/app/gemini/page.tsx
  src/components/markdown-renderer.tsx
  tailwind.config.ts
Labels: VSoC’24, HARD, BONUS-25

#9 gemini-vision UI
  package-lock.json
  package.json
  src/app/gemini-vision/page.tsx
  tailwind.config.ts
Labels: VSoC’24, HARD, BONUS-25

#12 changed old chat bubbles by using daisy UI! for Gemini bot
  src/app/gemini/page.tsx
Labels: VSoC’24, MEDIUM

#14 file input modal
  src/app/gemini-vision/page.tsx
  src/components/file-input-modal.tsx
Labels: VSoC’24, MEDIUM

#15 Text streaming
  .env.example
  package-lock.json
  package.json
  src/app/api/chat/gemini/route.ts
  src/app/gemini/page.tsx
Labels: VSoC’24, HARD, BONUS-50

#18 Adding Workflow Script
  .all-contributorsrc
  .github/workflows/add-contributors.yml
  Contributing.md
  README.md
Labels: VSoC’24, MEDIUM
